### PR TITLE
Replace 'dark' with 'harmful'

### LINKED ISSUE #25: Proposed Ethical Web Principle: Avoid enabling and amplifying dark patterns
The [W3C TAG Ethical Web Principles](https://www.w3.org/2001/tag/doc/ethical-web-principles/) mentions [enhancing individual control and power](https://www.w3.org/2001/tag/doc/ethical-web-principles/#control) and recognizes a few misbehaviors, yet focuses on decentralization, minimizing single points of failure, and enabling individual &amp; DIY developers. All of that is good, however there is the larger class of “dark pattern” harms to be named and explicitly avoided in specification and technology designs.

The Principles should explicitly note (either adding to or splitting off from “The web must enhance individuals' control and power”) the existence of “dark patterns” in web user interfaces (see [WP: Dark pattern](https://en.wikipedia.org/wiki/Dark_patterns) and [darkpatterns.org](https://www.darkpatterns.org/) for examples), with a statement similar to countering misinformation like:

We will avoid introducing technologies that create new or disproportionately enable, benefit, or amplify existing user interface dark patterns, such as confirmshaming, misdirection, friend spam, permissions pressuring or escalation, threat of data loss etc. We should also avoid new technologies that could be easily abused by existing dark patterns to more easily cause new or worse harms to users. We should design specifications that explicitly plan for and mitigate potential dark pattern abuses.

And cite either or both of those above two references. See also [twitter.com/darkpatterns](https://twitter.com/darkpatterns) for many more real world web examples.

We obviously won’t be able to prevent all dark patterns and their harms, but we can at least reduce some of them by calling them out, and avoiding new technologies that would increase the chance of users being harmed by existing and new dark patterns.

(Originally published at: https://tantek.com/2020/066/b2/avoid-enabling-amplifying-dark-patterns)

### PR DESCRIPTION
**Pull request by rhiaro**
Per https://github.com/w3ctag/ethical-web-principles/issues/25#issuecomment-932301439

### CODE REVIEW

**Review by LeaVerou — APPROVED** [review]

**Review by torgo — APPROVED** [review]
looks good.

**Review by tantek — CHANGES_REQUESTED** [review]
Would prefer using the phrase "manipulative design" rather than "harmful patterns" per https://github.com/w3ctag/ethical-web-principles/issues/25#issuecomment-934909547

**Review by torgo — APPROVED** [review]
looks great!

**Review by cynthia — APPROVED** [review]
LGTM.

**Pull request merged**
