### PR TITLE
Editorial: fixup links

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Review by jyasskin — APPROVED** [review]
Not that I have commit rights. :)

**Comment by marcoscaceres** [comment]
You have my vote for the TAG, @jyasskin! :laughing:

**Review by rhiaro — APPROVED** [review]

**Comment by marcoscaceres** [comment]
@rhiaro, do you have merge powers? I don't seem to have write access.

**Comment by torgo** [comment]
@marcoscaceres I fixed this access issue by adding you to @w3ctag/tag-irregulars and by giving that group write access.

**Pull request merged**
