### PR TITLE
Reference RFC7258 (BCP188) 'Pervasive Monitoring Is an Attack' where we mention the threat of surveillance.

### PR DESCRIPTION
**Pull request by hober**

### CODE REVIEW

**Review by torgo — APPROVED** [review]
I think this is a good idea. Thanks!

**Comment by hober** [comment]
This shouldn't be merged until #29 lands, at which point it will need to be updated in light of those changes.

**Comment by torgo** [comment]
Given the way we just changed how references work does this now need to be redone?

**Comment by hober** [comment]
> Given the way we just changed how references work does this now need to be redone?

Yeah, I'll try to fix this PR later today.

**Comment by hober** [comment]
Okay, this is ready to merge.

**Review by hadleybeeman — APPROVED** [review]

**Pull request merged**
