### PR TITLE
chore: fixup ReSpec usage

### PR DESCRIPTION
**Pull request by marcoscaceres**
Note, when citing something: 

```
<a data-cite="bib-entry#thing">the thing</a>
```

When taking explicitly about a particular document:
```
As discussed in [[[bib-entry-id]]] 
```

That will expand the title of the entry for you. 

More useful examples at: 
https://respec.org/docs/

However, I'm always around if you get stuck or need any help. Always happy to review also. Just ping!

### CODE REVIEW

**Comment by sidvishnoi** [comment]
With `github`, we get `edDraftURI` and `otherLinks["Repository"]` for free:
```diff
-    edDraftURI: "https://w3ctag.github.io/ethical-web-principles/",
+    github: "w3ctag/ethical-web-principles",
```

Also, following options are not supported (I don't know when they were):
```diff
-    inlineCSS: true,
-    noIDLIn: true,
-    noLegacyStyle: false,
```

Not sure about the `wg*` warnings. TAG is probably not in W3C API (`opentag` CG is there), so can't use `group` option directly.
Edit: TAG is in API, but we don't presently support it as it has no `type` and is the only group with `discr: "group"` (rest have `discr: "w3cgroup"`). Can make an exception on respec.org

**Comment by marcoscaceres** [comment]
Yeah, the config needs a big cleanup. We should do that as a followup.

**Review by torgo — APPROVED** [review]
looks good, thanks Marcos!

**Review by hadleybeeman — APPROVED** [review]
Thanks, Marcos!

**Pull request merged**
